In [34]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.ticker as ticker
import matplotlib.ticker as plticker
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

import matplotlib.pyplot as pyplot
import seaborn as sns

In [35]:
df = pd.read_csv('WC-final.csv')

In [36]:
df

,Unnamed: 0,country,goals,xg,crosses,boxtouches,passes,progpasses,takeons,progruns,tackles,interceptions,clearances,blocks,aerials,fouls,fouled,nsxg,results,year
0,1,germany,0.755385,0.614615,0.071538,0.436923,0.516923,0.344615,-0.132308,-0.006154,0.671538,-0.043846,-0.240769,-0.013846,-0.113846,-0.118462,0.043077,0.396154,1,14
1,1,argentina,0.536154,0.170769,0.166154,0.190769,-0.167692,-0.196154,0.557692,-0.204615,-0.063846,0.343077,0.177692,0.333846,0.128462,-0.034615,0.470000,0.228462,1,86
2,4,france,0.489231,0.231538,-0.124615,0.189231,0.123846,-0.039231,0.350769,0.080769,0.179231,0.126154,0.456923,-0.144615,0.266923,0.320000,0.460769,0.129231,1,18
3,0,france,0.445385,0.390769,0.243846,0.292308,0.091538,0.161538,0.260000,0.456154,0.383077,0.486154,-0.085385,-0.283077,0.160769,-0.057692,0.131538,0.456154,1,98
4,0,italy,0.286154,0.069231,0.013846,-0.040000,-0.095385,0.041538,0.054615,-0.230000,-0.101538,-0.220769,0.033846,0.198462,0.070000,0.350000,0.454615,-0.193846,1,82
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
277,0,saudi,-0.410000,-0.271538,-0.201538,-0.313077,0.321538,-0.080769,0.053077,-0.030769,-0.309231,-0.114615,0.203077,-0.212308,-0.440769,-0.219231,0.034615,-0.321538,32,2
278,0,panama,-0.420000,-0.230000,-0.150769,-0.435385,-0.687692,-0.408462,-0.256923,-0.586154,-0.629231,-0.560000,-0.145385,-0.404615,-0.509231,-0.173077,-0.193077,-0.369231,32,16
279,2,usa,-0.261538,-0.247692,0.028462,0.137692,-0.206923,-0.283077,-0.370769,-0.043846,0.068462,-0.391538,-0.449231,-0.298462,-0.048462,-0.444615,-0.049231,-0.153846,32,98
280,2,cameroon,-0.261538,-0.067692,0.040000,0.203077,-0.335385,-0.293846,0.150000,-0.086923,-0.338462,0.050000,-0.082308,0.077692,-0.226923,-0.030769,-0.130000,-0.094615,32,14
281,0,panama,-0.420000,-0.230000,-0.150769,-0.435385,-0.687692,-0.408462,-0.256923,-0.586154,-0.629231,-0.560000,-0.145385,-0.404615,-0.509231,-0.173077,-0.193077,-0.369231,32,18

In [37]:
df[df['country'] == 'panama']

,Unnamed: 0,country,goals,xg,crosses,boxtouches,passes,progpasses,takeons,progruns,tackles,interceptions,clearances,blocks,aerials,fouls,fouled,nsxg,results,year
278,0,panama,-0.42,-0.23,-0.150769,-0.435385,-0.687692,-0.408462,-0.256923,-0.586154,-0.629231,-0.56,-0.145385,-0.404615,-0.509231,-0.173077,-0.193077,-0.369231,32,16
281,0,panama,-0.42,-0.23,-0.150769,-0.435385,-0.687692,-0.408462,-0.256923,-0.586154,-0.629231,-0.56,-0.145385,-0.404615,-0.509231,-0.173077,-0.193077,-0.369231,32,18

In [38]:
df.shape

(282, 20)

In [39]:
df = df.drop([278])

In [40]:
df.shape

(281, 20)

In [41]:
df = df.drop(columns=['Unnamed: 0', 'year'])

In [42]:
from sklearn.preprocessing import OneHotEncoder

In [43]:
df = df.sort_values('passes')

In [44]:
df[df['country'] == 'panama']

,country,goals,xg,crosses,boxtouches,passes,progpasses,takeons,progruns,tackles,interceptions,clearances,blocks,aerials,fouls,fouled,nsxg,results
281,panama,-0.42,-0.23,-0.150769,-0.435385,-0.687692,-0.408462,-0.256923,-0.586154,-0.629231,-0.56,-0.145385,-0.404615,-0.509231,-0.173077,-0.193077,-0.369231,32

In [45]:
df = df.sample(frac=1)

In [46]:
enc=OneHotEncoder()
enc_data=pd.DataFrame(
    enc.fit_transform(df[['country']]).toarray())

In [47]:
df = df.drop(columns=['country'])

In [48]:
New_df=df.join(enc_data)

In [49]:
New_df

,goals,xg,crosses,boxtouches,passes,progpasses,takeons,progruns,tackles,interceptions,...,64,65,66,67,68,69,70,71,72,73
81,-0.040769,-0.080000,0.228462,0.070000,0.129231,-0.080000,0.228462,0.196923,-0.052308,-0.171538,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
252,-0.247692,-0.058462,0.023077,-0.005385,-0.083077,-0.176154,0.573846,-0.158462,-0.038462,-0.166923,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
225,0.055385,0.266154,0.076923,0.214615,0.210000,0.326923,-0.112308,0.261538,0.226923,0.198462,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
43,0.781538,0.256154,0.016923,0.298462,-0.303077,-0.243846,0.117692,0.115385,-0.035385,-0.245385,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
52,0.472308,0.458462,-0.023846,0.078462,0.416923,0.273846,0.693077,0.513077,0.130000,0.178462,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207,-0.093077,-0.197692,-0.366923,-0.434615,0.531538,0.181538,-0.248462,-0.085385,0.169231,0.879231,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
163,0.689231,0.773846,-0.020769,0.551538,-0.054615,-0.101538,-0.112308,-0.080000,0.333077,0.871538,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
196,0.243846,0.064615,0.097692,0.312308,0.330769,0.399231,0.216154,-0.051538,0.349231,0.529231,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
50,-0.040769,0.086154,0.800000,0.509231,0.105385,0.273077,-0.303846,0.075385,-0.152308,0.050769,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
153,0.264615,0.005385,-0.148462,-0.049231,-0.178462,-0.246923,-0.060000,-0.232308,-0.256923,-0.500769,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [50]:
New_df = New_df.dropna()

In [51]:
New_df.to_csv('hotData.csv', index=False)

In [32]:
df = pd.read_csv('hotData.csv')

In [33]:
df

,goals,xg,crosses,boxtouches,passes,progpasses,takeons,progruns,tackles,interceptions,...,64,65,66,67,68,69,70,71,72,73
0,0.073846,0.256154,0.146154,0.057692,0.596923,0.017692,0.834615,1.092308,0.728462,0.707692,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.373846,0.166154,0.297692,0.044615,0.316923,-0.044615,0.379231,0.212308,0.300769,0.247692,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.122308,0.143846,-0.026923,-0.242308,-0.064615,-0.245385,-0.090000,-0.073846,0.261538,0.106154,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,-0.103077,-0.270769,-0.020000,-0.350000,-0.159231,0.011538,-0.186154,-0.476923,-0.342308,-0.209231,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.553077,0.411538,-0.104615,0.026923,-0.352308,-0.238462,-0.254615,-0.268462,-0.125385,0.029231,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
276,-0.085385,0.104615,0.336923,0.406923,0.588462,0.594615,0.401538,0.588462,0.070000,0.294615,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
277,-0.193846,-0.290769,-0.075385,-0.372308,-0.380000,-0.211538,-0.340000,-0.636923,-0.611538,-0.588462,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
278,0.373846,0.110000,0.030000,0.300769,0.497692,-0.213846,0.450000,0.743077,0.881538,0.370769,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
279,0.157692,-0.186923,0.221538,0.010769,0.264615,0.141538,0.155385,-0.065385,0.109231,-0.039231,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
280,-0.066154,0.076154,0.387692,0.673846,0.050769,0.183077,0.283077,0.358462,0.179231,-0.340769,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0