In [14]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_absolute_percentage_error

from sklearn.ensemble import AdaBoostRegressor
from sklearn.tree import DecisionTreeRegressor

In [15]:
df = pd.read_csv('wc-7.csv')

In [16]:
df = df.drop(columns=['country', 'year'])

In [17]:
y = df['results']
X = df.drop(columns=['results'])

X_train, X_test, y_train, y_test = train_test_split(
     X, y, test_size=0.10, random_state=2)

In [18]:
regr_1 = DecisionTreeRegressor()

regr_2 = AdaBoostRegressor(
    DecisionTreeRegressor(max_depth=4), n_estimators=300, random_state=42
)

In [19]:
regr_1.fit(X_train, y_train)
regr_2.fit(X_train, y_train)

y_1 = regr_1.predict(X_test)
y_2 = regr_2.predict(X_test)

In [20]:
print('r2 score: '+str(r2_score(y_test, y_1)))
print('RMSE : '+str(np.sqrt(mean_squared_error(y_test, y_1))))
print('MSE: '+str(mean_squared_error(y_test, y_1)))
print('MAE: '+str(mean_absolute_error(y_test, y_1)))
print('MAPE: '+str(mean_absolute_percentage_error(y_test, y_1)))


print('---------------')
print('r2 score: '+str(r2_score(y_test, y_2)))
print('RMSE : '+str(np.sqrt(mean_squared_error(y_test, y_2))))
print('MSE: '+str(mean_squared_error(y_test, y_2)))
print('MAE: '+str(mean_absolute_error(y_test, y_2)))
print('MAPE: '+str(mean_absolute_percentage_error(y_test, y_2)))

r2 score: -0.016883116883116944
RMSE : 7.779282831939609
MSE: 60.51724137931034
MAE: 6.310344827586207
MAPE: 0.8234635781843022
---------------
r2 score: 0.3431465482024345
RMSE : 6.252278087794902
MSE: 39.09098128712027
MAE: 5.055498578565173
MAPE: 0.7369019131045085

In [15]:
# MAPE: 0.8162758623484649

# r2 score: -0.016883116883116944
# RMSE : 7.779282831939609
# MSE: 60.51724137931034
# MAE: 6.310344827586207
# MAPE: 0.8234635781843022
# ---------------
# r2 score: 0.3431465482024345
# RMSE : 6.252278087794902
# MSE: 39.09098128712027
# MAE: 5.055498578565173
# MAPE: 0.7369019131045085





# w/ date
# r2 score: -0.1258141858141859
# RMSE : 8.18535277187245
# MSE: 67.0
# MAE: 6.793103448275862
# MAPE: 0.8375431834617296
# ---------------
# r2 score: 0.44179338719087413
# RMSE : 5.763702173779817
# MSE: 33.22026274803418
# MAE: 4.429678145327355
# MAPE: 0.662228684613377

In [9]:
data = {'y_test': y_test, 'y_pred': y_2}
new_df = pd.DataFrame(data)
diff = (new_df['y_test'] - (new_df['y_pred'])).abs()
new_df['diff'] = diff
new_df = new_df.sort_values(by='diff', ascending=True)

In [10]:
new_df

     y_test     y_pred       diff
7        24  23.974359   0.025641
66       11  10.609272   0.390728
13       27  26.595238   0.404762
89       11  11.500000   0.500000
245      22  21.400000   0.600000
99        9  10.324324   1.324324
142      21  19.461538   1.538462
141      21  18.865672   2.134328
11       27  24.469388   2.530612
152      13  15.633333   2.633333
176      12  15.000000   3.000000
101      19  15.458333   3.541667
3        21  24.684211   3.684211
118       3   7.590909   4.590909
77       26  21.382353   4.617647
35       15   9.800000   5.200000
250      18  23.321429   5.321429
128      26  20.608696   5.391304
112       6  12.129032   6.129032
113      19  12.076923   6.923077
252      17   9.666667   7.333333
133       3  10.536364   7.536364
157       1   8.808219   7.808219
29        7  14.929293   7.929293
191      16   6.454545   9.545455
93       24  13.964286  10.035714
127       6  16.460177  10.460177
173      14  25.515152  11.515152
227      23   9.035714  13.964286