In [248]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.ticker as ticker
import matplotlib.ticker as plticker
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

import matplotlib.pyplot as pyplot
import seaborn as sns

In [249]:
df = pd.read_csv('WC-stats.csv')

In [250]:
df.head()

,Unnamed: 0,goals_z,xg_z,crosses_z,boxtouches_z,passes_z,progpasses_z,takeons_z,progruns_z,tackles_z,interceptions_z,clearances_z,blocks_z,aerials_z,fouls_z,fouled_z,nsxg_z,results
0,Brazil98,0.423077,0.146923,-0.136154,-0.030000,0.429231,0.037692,0.244615,-0.220000,0.216154,0.270000,-0.076923,-0.097692,-0.020000,-0.224615,0.100769,-0.124615,2
1,Brazil94,0.216923,0.348462,0.031538,0.158462,0.835385,0.626923,0.270000,0.266923,1.143846,0.834615,-0.059231,-0.134615,0.196923,-0.016923,0.033846,0.146923,1
2,Brazil90,0.113846,0.392308,0.599231,0.513846,0.833077,0.405385,0.521538,1.139231,1.109231,0.859231,0.084615,0.103077,0.683846,0.213846,0.353846,0.786923,9
3,Brazil86,0.479231,0.609231,0.227692,0.450769,0.770769,0.042308,0.337692,0.927692,0.506923,1.015385,0.020769,0.381538,0.038462,0.039231,0.022308,0.692308,5
4,Brazil82,0.877692,0.773846,0.428462,0.659231,0.754615,0.335385,0.023077,0.638462,0.493846,0.637692,-0.117692,-0.033846,0.572308,-0.016154,-0.096923,0.890769,5

In [251]:
df = df.rename(columns={"Unnamed: 0": "country"}, errors="raise")

In [252]:
sers = df['country']

In [253]:
year = []
count = 0
for i in sers:
    num = (((i[-2]) + i[-1]))
    year.append(int(num))

In [254]:
len(year)

257

In [255]:
df['year'] = year

In [256]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 257 entries, 0 to 256
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   country          257 non-null    object
 1   goals_z          257 non-null    float64
 2   xg_z             257 non-null    float64
 3   crosses_z        257 non-null    float64
 4   boxtouches_z     257 non-null    float64
 5   passes_z         257 non-null    float64
 6   progpasses_z     257 non-null    float64
 7   takeons_z        257 non-null    float64
 8   progruns_z       257 non-null    float64
 9   tackles_z        257 non-null    float64
 10  interceptions_z  257 non-null    float64
 11  clearances_z     257 non-null    float64
 12  blocks_z         257 non-null    float64
 13  aerials_z        257 non-null    float64
 14  fouls_z          257 non-null    float64
 15  fouled_z         257 non-null    float64
 16  nsxg_z           257 non-null    float64
 17  results          257 non-null    int64
 18  year             257 non-null    int64
dtypes: float64(16), int64(2), object(1)
memory usage: 38.3+ KB

In [257]:
df['year'].value_counts().sum()

257

In [258]:
df

,country,goals_z,xg_z,crosses_z,boxtouches_z,passes_z,progpasses_z,takeons_z,progruns_z,tackles_z,interceptions_z,clearances_z,blocks_z,aerials_z,fouls_z,fouled_z,nsxg_z,results,year
0,Brazil98,0.423077,0.146923,-0.136154,-0.030000,0.429231,0.037692,0.244615,-0.220000,0.216154,0.270000,-0.076923,-0.097692,-0.020000,-0.224615,0.100769,-0.124615,2,98
1,Brazil94,0.216923,0.348462,0.031538,0.158462,0.835385,0.626923,0.270000,0.266923,1.143846,0.834615,-0.059231,-0.134615,0.196923,-0.016923,0.033846,0.146923,1,94
2,Brazil90,0.113846,0.392308,0.599231,0.513846,0.833077,0.405385,0.521538,1.139231,1.109231,0.859231,0.084615,0.103077,0.683846,0.213846,0.353846,0.786923,9,90
3,Brazil86,0.479231,0.609231,0.227692,0.450769,0.770769,0.042308,0.337692,0.927692,0.506923,1.015385,0.020769,0.381538,0.038462,0.039231,0.022308,0.692308,5,86
4,Brazil82,0.877692,0.773846,0.428462,0.659231,0.754615,0.335385,0.023077,0.638462,0.493846,0.637692,-0.117692,-0.033846,0.572308,-0.016154,-0.096923,0.890769,5,82
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
252,Colombia90,0.073077,0.004615,-0.013077,0.047692,0.873846,0.790769,0.200769,-0.084615,0.260000,1.156923,-0.149231,0.108462,-0.160769,0.427692,0.540769,-0.071538,14,90
253,Colombia94,0.013846,0.266923,-0.103846,0.443077,1.092308,0.601538,0.500769,-0.234615,0.880000,1.216154,-0.359231,0.058462,-0.150000,0.290000,-0.176154,0.568462,19,94
254,Colombia98,-0.261538,-0.169231,-0.216923,-0.154615,0.068462,-0.088462,0.183077,0.316154,-0.177692,0.080769,-0.166154,-0.361538,-0.270000,0.290000,0.245385,-0.173077,21,98
255,Colombia14,0.781538,0.256154,0.016923,0.298462,-0.303077,-0.243846,0.117692,0.115385,-0.035385,-0.245385,-0.143077,-0.047692,-0.237692,0.343846,0.417692,0.353077,5,14
256,Colombia18,0.313077,-0.103077,0.029231,-0.319231,-0.093846,-0.152308,-0.142308,-0.181538,0.058462,-0.141538,0.016923,-0.018462,0.121538,0.212308,0.083077,-0.171538,9,18

In [259]:
country = df['country']

In [260]:
country

0        Brazil98
1        Brazil94
2        Brazil90
3        Brazil86
4        Brazil82
          ...
252    Colombia90
253    Colombia94
254    Colombia98
255    Colombia14
256    Colombia18
Name: country, Length: 257, dtype: object

In [261]:
country = []
for i in sers:
    land = (i[:-2])
    country.append(str(land))

In [262]:
df['country'] = country

In [263]:
df

,country,goals_z,xg_z,crosses_z,boxtouches_z,passes_z,progpasses_z,takeons_z,progruns_z,tackles_z,interceptions_z,clearances_z,blocks_z,aerials_z,fouls_z,fouled_z,nsxg_z,results,year
0,Brazil,0.423077,0.146923,-0.136154,-0.030000,0.429231,0.037692,0.244615,-0.220000,0.216154,0.270000,-0.076923,-0.097692,-0.020000,-0.224615,0.100769,-0.124615,2,98
1,Brazil,0.216923,0.348462,0.031538,0.158462,0.835385,0.626923,0.270000,0.266923,1.143846,0.834615,-0.059231,-0.134615,0.196923,-0.016923,0.033846,0.146923,1,94
2,Brazil,0.113846,0.392308,0.599231,0.513846,0.833077,0.405385,0.521538,1.139231,1.109231,0.859231,0.084615,0.103077,0.683846,0.213846,0.353846,0.786923,9,90
3,Brazil,0.479231,0.609231,0.227692,0.450769,0.770769,0.042308,0.337692,0.927692,0.506923,1.015385,0.020769,0.381538,0.038462,0.039231,0.022308,0.692308,5,86
4,Brazil,0.877692,0.773846,0.428462,0.659231,0.754615,0.335385,0.023077,0.638462,0.493846,0.637692,-0.117692,-0.033846,0.572308,-0.016154,-0.096923,0.890769,5,82
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
252,Colombia,0.073077,0.004615,-0.013077,0.047692,0.873846,0.790769,0.200769,-0.084615,0.260000,1.156923,-0.149231,0.108462,-0.160769,0.427692,0.540769,-0.071538,14,90
253,Colombia,0.013846,0.266923,-0.103846,0.443077,1.092308,0.601538,0.500769,-0.234615,0.880000,1.216154,-0.359231,0.058462,-0.150000,0.290000,-0.176154,0.568462,19,94
254,Colombia,-0.261538,-0.169231,-0.216923,-0.154615,0.068462,-0.088462,0.183077,0.316154,-0.177692,0.080769,-0.166154,-0.361538,-0.270000,0.290000,0.245385,-0.173077,21,98
255,Colombia,0.781538,0.256154,0.016923,0.298462,-0.303077,-0.243846,0.117692,0.115385,-0.035385,-0.245385,-0.143077,-0.047692,-0.237692,0.343846,0.417692,0.353077,5,14
256,Colombia,0.313077,-0.103077,0.029231,-0.319231,-0.093846,-0.152308,-0.142308,-0.181538,0.058462,-0.141538,0.016923,-0.018462,0.121538,0.212308,0.083077,-0.171538,9,18

In [264]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 257 entries, 0 to 256
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   country          257 non-null    object
 1   goals_z          257 non-null    float64
 2   xg_z             257 non-null    float64
 3   crosses_z        257 non-null    float64
 4   boxtouches_z     257 non-null    float64
 5   passes_z         257 non-null    float64
 6   progpasses_z     257 non-null    float64
 7   takeons_z        257 non-null    float64
 8   progruns_z       257 non-null    float64
 9   tackles_z        257 non-null    float64
 10  interceptions_z  257 non-null    float64
 11  clearances_z     257 non-null    float64
 12  blocks_z         257 non-null    float64
 13  aerials_z        257 non-null    float64
 14  fouls_z          257 non-null    float64
 15  fouled_z         257 non-null    float64
 16  nsxg_z           257 non-null    float64
 17  results          257 non-null    int64
 18  year             257 non-null    int64
dtypes: float64(16), int64(2), object(1)
memory usage: 38.3+ KB

## Add: GDP per capita, Population, ODDSET probability, Rank, Continent, Confederation

- ODDSET probability. We convert bookmaker odds provided by the German state betting agency ODDSET into winning probabilities. The variable hence reflects the probability for each team to win the respective World Cup1.

- FIFA rank. The FIFA ranking system ranks all national teams based on their performance over the last four years (source: http://de.fifa.com/ worldranking/index.html).

- Continent. A dummy variable indicating if a national team is from the same continent as the host of the World Cup (including the host itself).

- Confederation. This categorical variable comprises the teams’ confederation with six possible values: Africa (CAF); Asia (AFC); Europe (UEFA); North, Central America and Caribbean (CONCACAF); Oceania (OFC); South America (CONMEBOL).

In [269]:
df = df.sort_values(by=['year'])

In [273]:
df['year'].value_counts()

10    30
14    30
2     28
18    28
98    28
6     25
90    24
82    23
86    20
94    20
16     1
Name: year, dtype: int64

In [277]:
df['country'].value_counts()

Spain         10
Brazil        10
Argentina     10
Germany       10
England        9
              ..
ElSalvador     1
Slovakia       1
Iceland        1
Bosnia         1
Jamaica        1
Name: country, Length: 70, dtype: int64

In [278]:
df[df['country'] == 'Spain']

,country,goals_z,xg_z,crosses_z,boxtouches_z,passes_z,progpasses_z,takeons_z,progruns_z,tackles_z,interceptions_z,clearances_z,blocks_z,aerials_z,fouls_z,fouled_z,nsxg_z,results,year
20,Spain,0.451538,0.495385,-0.012308,0.182308,0.003077,-0.222308,0.012308,0.130769,0.147692,-0.010000,-0.193846,-0.215385,0.151538,-0.287692,0.157692,0.132308,10,2
21,Spain,0.881538,1.015385,0.637692,0.533077,0.500769,0.266154,0.676923,0.080000,0.447692,1.215385,-0.337692,-0.442308,-0.273077,0.041538,0.093077,0.650769,23,6
22,Spain,0.180000,0.539231,0.383077,0.868462,1.156923,0.320000,0.616923,1.432308,0.753846,0.910000,0.026923,0.636154,0.286154,-0.138462,0.464615,0.762308,1,10
23,Spain,0.243846,0.536154,-0.076154,0.596923,0.770769,-0.052308,-0.182308,0.489231,1.146154,0.657692,-0.383077,-0.379231,0.017692,-0.391538,0.333077,0.412308,9,14
24,Spain,0.190769,0.680769,0.319231,0.763077,1.410769,0.267692,0.516923,0.981538,0.420000,0.449231,-0.392308,0.094615,-0.016923,-0.410000,0.195385,0.726154,5,18
108,Spain,-0.133846,0.256154,0.170769,0.283077,0.134615,0.325385,-0.096923,0.262308,0.286154,0.152308,0.067692,-0.172308,0.236154,0.000769,0.127692,0.303077,12,82
109,Spain,0.566154,0.463077,0.130000,0.464615,-0.154615,0.110769,-0.134615,-0.115385,-0.296154,-0.282308,-0.366154,-0.210000,0.037692,-0.263846,0.064615,0.353077,7,86
110,Spain,0.319231,0.181538,0.343077,0.478462,0.093077,0.240769,0.277692,0.030769,-0.124615,0.053077,0.038462,0.255385,-0.107692,0.080769,0.174615,0.254615,10,90
111,Spain,0.417692,0.250000,0.259231,0.076154,-0.371538,-0.307692,0.165385,-0.083846,-0.407692,-0.237692,0.124615,-0.123846,0.232308,0.385385,-0.070000,0.069231,8,94
112,Spain,0.689231,0.773846,-0.020769,0.551538,-0.054615,-0.101538,-0.112308,-0.080000,0.333077,0.871538,-0.318462,0.173077,0.363846,-0.326923,-0.166923,0.448462,17,98