In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_absolute_percentage_error

import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib.colors import SymLogNorm

from sklearn import linear_model

In [2]:
df = pd.read_csv('hotData.csv')

In [3]:
y = df['results']
X = df.drop(columns=['results'])

X_train, X_test, y_train, y_test = train_test_split(
     X, y, test_size=0.10, random_state=2)

In [4]:
clf = linear_model.PoissonRegressor( tol=.0610)

In [5]:
clf.fit(X_train, y_train)

PoissonRegressor(tol=0.061)

In [6]:
pred_test= clf.predict(X_test)

In [7]:
print('RMSE : '+str(np.sqrt(mean_squared_error(y_test,pred_test)))) 
print('R2 : '+str(r2_score(y_test, pred_test)))
print('MSE: '+str(mean_squared_error(y_test, pred_test)))
print('MAE: '+str(mean_absolute_error(y_test, pred_test)))
print('MAPE: '+str(mean_absolute_percentage_error(y_test, pred_test)))

RMSE : 7.208204491427294
R2 : 0.32183542409619725
MSE: 51.95821199023261
MAE: 5.762024265784867
MAPE: 0.8365621848001213

In [8]:
# mape = 1.279883454957357
# fit_intercept=False / mape = .8045208314190103
# alpha=1.9 / mape = 7945596398916809
# alpha=2.061 / mape = 7945052390518497
# alpha=2.000 / .7945024580554179
# alpha=1.95999 / .7943855674740651
# tol=.0610 / mape = .7941576732936836

In [9]:
data = {'y_test': y_test, 'y_pred': pred_test}
new_df = pd.DataFrame(data)
diff = (new_df['y_test'] - new_df['y_pred']).abs()
new_df['diff'] = diff
new_df = new_df.sort_values(by='diff', ascending=True)

In [10]:
new_df = new_df.sort_values(by='diff', ascending=True)
new_df['y_pred'] = round(new_df['y_pred'], 1)
prediction=new_df['y_pred']
reality=new_df['y_test']

In [11]:
new_df

     y_test  y_pred       diff
250      10     9.5   0.466072
66       12    12.6   0.552862
101      13    12.4   0.609337
176      19    19.7   0.748969
152      15    16.3   1.306271
77       16    17.3   1.330878
11       27    24.6   2.408137
127      15    12.5   2.466424
35       23    19.8   3.239570
99        8    11.3   3.314159
89       12    15.5   3.496175
13       25    20.9   4.133163
7        30    25.6   4.381356
245       9    13.6   4.602002
157      15    10.4   4.639729
118       7    12.1   5.091261
93       24    18.9   5.129899
191      20    14.6   5.399044
227       4    10.6   6.592223
141      24    16.4   7.639114
173       3    10.8   7.800150
29       11    19.7   8.727031
133      22    13.0   8.960944
142       5    14.2   9.191155
113       4    13.9   9.907427
112      28    17.9  10.096846
252      28    16.2  11.751025
128      31    16.1  14.865576
3         2    20.3  18.251903