In [1]:
import pandas as pd

In [2]:
matches = pd.read_csv("matches.csv", index_col=0)

In [3]:
matches.head()

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
1,2021-08-15,16:30,Premier League,Matchweek 1,Sun,Away,L,0,1,Tottenham,...,Match Report,NaN,18.0,4.0,16.9,1.0,0.0,0.0,2022,Manchester City
2,2021-08-21,15:00,Premier League,Matchweek 2,Sat,Home,W,5,0,Norwich City,...,Match Report,NaN,16.0,4.0,17.3,1.0,0.0,0.0,2022,Manchester City
3,2021-08-28,12:30,Premier League,Matchweek 3,Sat,Home,W,5,0,Arsenal,...,Match Report,NaN,25.0,10.0,14.3,0.0,0.0,0.0,2022,Manchester City
4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Away,W,1,0,Leicester City,...,Match Report,NaN,25.0,8.0,14.0,0.0,0.0,0.0,2022,Manchester City
6,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Home,D,0,0,Southampton,...,Match Report,NaN,16.0,1.0,15.7,1.0,0.0,0.0,2022,Manchester City

In [4]:
matches.shape

(1520, 27)

In [5]:
# 2 seasons * 20 squads * 38 matches

2 * 20 * 38

1520

In [6]:
# Missing Liverpool 2021-2022
matches["team"].value_counts()

Manchester City             76
Wolverhampton Wanderers     76
Burnley                     76
Leeds United                76
Everton                     76
Southampton                 76
Aston Villa                 76
Liverpool                   76
Newcastle United            76
Crystal Palace              76
Brighton and Hove Albion    76
Leicester City              76
West Ham United             76
Manchester United           76
Arsenal                     76
Tottenham Hotspur           76
Chelsea                     76
Brentford                   38
Watford                     38
Norwich City                38
Fulham                      38
West Bromwich Albion        38
Sheffield United            38
Name: team, dtype: int64

In [7]:
matches[matches["team"] == "Liverpool"].sort_values("date")

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
1,2020-09-12,17:30,Premier League,Matchweek 1,Sat,Home,W,4,3,Leeds United,...,Match Report,NaN,20.0,4.0,17.0,0.0,2.0,2.0,2021,Liverpool
2,2020-09-20,16:30,Premier League,Matchweek 2,Sun,Away,W,2,0,Chelsea,...,Match Report,NaN,17.0,5.0,17.7,1.0,0.0,0.0,2021,Liverpool
4,2020-09-28,20:00,Premier League,Matchweek 3,Mon,Home,W,3,1,Arsenal,...,Match Report,NaN,21.0,9.0,16.8,0.0,0.0,0.0,2021,Liverpool
6,2020-10-04,19:15,Premier League,Matchweek 4,Sun,Away,L,2,7,Aston Villa,...,Match Report,NaN,14.0,8.0,15.8,1.0,0.0,0.0,2021,Liverpool
7,2020-10-17,12:30,Premier League,Matchweek 5,Sat,Away,D,2,2,Everton,...,Match Report,NaN,22.0,8.0,15.0,1.0,0.0,0.0,2021,Liverpool
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55,2022-04-30,12:30,Premier League,Matchweek 35,Sat,Away,W,1,0,Newcastle Utd,...,Match Report,NaN,24.0,11.0,17.4,2.0,0.0,0.0,2022,Liverpool
57,2022-05-07,19:45,Premier League,Matchweek 36,Sat,Home,D,1,1,Tottenham,...,Match Report,NaN,22.0,3.0,18.6,0.0,0.0,0.0,2022,Liverpool
58,2022-05-10,20:00,Premier League,Matchweek 33,Tue,Away,W,2,1,Aston Villa,...,Match Report,NaN,17.0,5.0,15.4,2.0,0.0,0.0,2022,Liverpool
60,2022-05-17,19:45,Premier League,Matchweek 37,Tue,Away,W,2,1,Southampton,...,Match Report,NaN,24.0,5.0,17.5,0.0,0.0,0.0,2022,Liverpool
61,2022-05-22,16:00,Premier League,Matchweek 38,Sun,Home,W,3,1,Wolves,...,Match Report,NaN,29.0,7.0,15.2,0.0,0.0,0.0,2022,Liverpool

In [8]:
matches["round"].value_counts()

Matchweek 1     40
Matchweek 29    40
Matchweek 22    40
Matchweek 23    40
Matchweek 24    40
Matchweek 25    40
Matchweek 26    40
Matchweek 27    40
Matchweek 28    40
Matchweek 31    40
Matchweek 2     40
Matchweek 32    40
Matchweek 30    40
Matchweek 34    40
Matchweek 35    40
Matchweek 36    40
Matchweek 33    40
Matchweek 37    40
Matchweek 21    40
Matchweek 20    40
Matchweek 19    40
Matchweek 18    40
Matchweek 3     40
Matchweek 4     40
Matchweek 5     40
Matchweek 6     40
Matchweek 7     40
Matchweek 8     40
Matchweek 9     40
Matchweek 10    40
Matchweek 11    40
Matchweek 12    40
Matchweek 13    40
Matchweek 14    40
Matchweek 15    40
Matchweek 16    40
Matchweek 17    40
Matchweek 38    40
Name: round, dtype: int64

In [9]:
matches.dtypes

date             object
time             object
comp             object
round            object
day              object
venue            object
result           object
gf                int64
ga                int64
opponent         object
xg              float64
xga             float64
poss            float64
attendance      float64
captain          object
formation        object
referee          object
match report     object
notes           float64
sh              float64
sot             float64
dist            float64
fk              float64
pk              float64
pkatt           float64
season            int64
team             object
dtype: object

In [10]:
del matches["comp"]

In [11]:
del matches["notes"]

In [12]:
matches["date"] = pd.to_datetime(matches["date"])

In [13]:
matches["target"] = (matches["result"] == "W").astype("int")

In [14]:
matches

,date,time,round,day,venue,result,gf,ga,opponent,xg,...,match report,sh,sot,dist,fk,pk,pkatt,season,team,target
1,2021-08-15,16:30,Matchweek 1,Sun,Away,L,0,1,Tottenham,1.9,...,Match Report,18.0,4.0,16.9,1.0,0.0,0.0,2022,Manchester City,0
2,2021-08-21,15:00,Matchweek 2,Sat,Home,W,5,0,Norwich City,2.7,...,Match Report,16.0,4.0,17.3,1.0,0.0,0.0,2022,Manchester City,1
3,2021-08-28,12:30,Matchweek 3,Sat,Home,W,5,0,Arsenal,3.8,...,Match Report,25.0,10.0,14.3,0.0,0.0,0.0,2022,Manchester City,1
4,2021-09-11,15:00,Matchweek 4,Sat,Away,W,1,0,Leicester City,2.9,...,Match Report,25.0,8.0,14.0,0.0,0.0,0.0,2022,Manchester City,1
6,2021-09-18,15:00,Matchweek 5,Sat,Home,D,0,0,Southampton,1.1,...,Match Report,16.0,1.0,15.7,1.0,0.0,0.0,2022,Manchester City,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38,2021-05-02,19:15,Matchweek 34,Sun,Away,L,0,4,Tottenham,0.5,...,Match Report,8.0,1.0,17.4,0.0,0.0,0.0,2021,Sheffield United,0
39,2021-05-08,15:00,Matchweek 35,Sat,Home,L,0,2,Crystal Palace,0.7,...,Match Report,7.0,0.0,11.4,1.0,0.0,0.0,2021,Sheffield United,0
40,2021-05-16,19:00,Matchweek 36,Sun,Away,W,1,0,Everton,1.6,...,Match Report,10.0,3.0,17.0,0.0,0.0,0.0,2021,Sheffield United,1
41,2021-05-19,18:00,Matchweek 37,Wed,Away,L,0,1,Newcastle Utd,0.8,...,Match Report,11.0,1.0,16.0,1.0,0.0,0.0,2021,Sheffield United,0
42,2021-05-23,16:00,Matchweek 38,Sun,Home,W,1,0,Burnley,0.6,...,Match Report,12.0,3.0,17.0,0.0,0.0,0.0,2021,Sheffield United,1

In [15]:
matches["venue_code"] = matches["venue"].astype("category").cat.codes

In [16]:
matches["opp_code"] = matches["opponent"].astype("category").cat.codes

In [17]:
matches["hour"] = matches["time"].str.replace(":.+", "", regex=True).astype("int")

In [18]:
matches["day_code"] = matches["date"].dt.dayofweek

In [19]:
matches

,date,time,round,day,venue,result,gf,ga,opponent,xg,...,fk,pk,pkatt,season,team,target,venue_code,opp_code,hour,day_code
1,2021-08-15,16:30,Matchweek 1,Sun,Away,L,0,1,Tottenham,1.9,...,1.0,0.0,0.0,2022,Manchester City,0,0,18,16,6
2,2021-08-21,15:00,Matchweek 2,Sat,Home,W,5,0,Norwich City,2.7,...,1.0,0.0,0.0,2022,Manchester City,1,1,15,15,5
3,2021-08-28,12:30,Matchweek 3,Sat,Home,W,5,0,Arsenal,3.8,...,0.0,0.0,0.0,2022,Manchester City,1,1,0,12,5
4,2021-09-11,15:00,Matchweek 4,Sat,Away,W,1,0,Leicester City,2.9,...,0.0,0.0,0.0,2022,Manchester City,1,0,10,15,5
6,2021-09-18,15:00,Matchweek 5,Sat,Home,D,0,0,Southampton,1.1,...,1.0,0.0,0.0,2022,Manchester City,0,1,17,15,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38,2021-05-02,19:15,Matchweek 34,Sun,Away,L,0,4,Tottenham,0.5,...,0.0,0.0,0.0,2021,Sheffield United,0,0,18,19,6
39,2021-05-08,15:00,Matchweek 35,Sat,Home,L,0,2,Crystal Palace,0.7,...,1.0,0.0,0.0,2021,Sheffield United,0,1,6,15,5
40,2021-05-16,19:00,Matchweek 36,Sun,Away,W,1,0,Everton,1.6,...,0.0,0.0,0.0,2021,Sheffield United,1,0,7,19,6
41,2021-05-19,18:00,Matchweek 37,Wed,Away,L,0,1,Newcastle Utd,0.8,...,1.0,0.0,0.0,2021,Sheffield United,0,0,14,18,2
42,2021-05-23,16:00,Matchweek 38,Sun,Home,W,1,0,Burnley,0.6,...,0.0,0.0,0.0,2021,Sheffield United,1,1,4,16,6

In [20]:
from sklearn.ensemble import RandomForestClassifier

In [21]:
rf = RandomForestClassifier(n_estimators=50, min_samples_split=10, random_state=1)

In [22]:
train = matches[matches["date"] < '2022-01-01']

In [23]:
test = matches[matches["date"] > '2022-01-01']

In [24]:
predictors = ["venue_code", "opp_code", "hour", "day_code"]

In [25]:
rf.fit(train[predictors], train["target"])

RandomForestClassifier(min_samples_split=10, n_estimators=50, random_state=1)

In [26]:
preds = rf.predict(test[predictors])

In [27]:
from sklearn.metrics import accuracy_score

In [28]:
error = accuracy_score(test["target"], preds)

In [29]:
error

0.6056701030927835

In [30]:
combined = pd.DataFrame(dict(actual=test["target"], predicted=preds))

In [31]:
pd.crosstab(index=combined["actual"], columns=combined["predicted"])

predicted    0   1
actual
0          186  47
1          106  49

In [32]:
from sklearn.metrics import precision_score

precision_score(test["target"], preds)

0.5104166666666666

In [33]:
grouped_matches = matches.groupby("team")

In [34]:
group = grouped_matches.get_group("Manchester City").sort_values("date")

In [35]:
def rolling_averages(group, cols, new_cols):
    group = group.sort_values("date")
    rolling_stats = group[cols].rolling(3, closed='left').mean()
    group[new_cols] = rolling_stats
    group = group.dropna(subset=new_cols)
    return group

In [36]:
cols = ["gf", "ga", "sh", "sot", "dist", "fk", "pk", "pkatt"]
new_cols = [f"{c}_rolling" for c in cols]

rolling_averages(group, cols, new_cols)

,date,time,round,day,venue,result,gf,ga,opponent,xg,...,hour,day_code,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
5,2020-10-17,17:30,Matchweek 5,Sat,Home,W,1,0,Arsenal,1.5,...,17,5,2.000000,2.333333,17.333333,4.666667,18.900000,1.333333,0.333333,0.333333
7,2020-10-24,12:30,Matchweek 6,Sat,Away,D,1,1,West Ham,1.1,...,12,5,1.333333,2.000000,17.333333,3.666667,17.733333,0.666667,0.000000,0.000000
9,2020-10-31,12:30,Matchweek 7,Sat,Away,W,1,0,Sheffield Utd,1.5,...,12,5,1.000000,0.666667,16.666667,4.333333,18.233333,0.666667,0.000000,0.000000
11,2020-11-08,16:30,Matchweek 8,Sun,Home,D,1,1,Liverpool,1.6,...,16,6,1.000000,0.333333,14.333333,6.666667,18.466667,1.000000,0.000000,0.000000
12,2020-11-21,17:30,Matchweek 9,Sat,Away,L,0,2,Tottenham,1.3,...,17,5,1.000000,0.666667,12.000000,5.666667,19.366667,1.000000,0.000000,0.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52,2022-04-30,17:30,Matchweek 35,Sat,Away,W,4,0,Leeds United,2.7,...,17,5,3.333333,1.000000,16.000000,5.333333,16.700000,0.333333,0.333333,0.333333
54,2022-05-08,16:30,Matchweek 36,Sun,Home,W,5,0,Newcastle Utd,3.1,...,16,6,4.000000,0.333333,18.666667,6.000000,16.333333,0.000000,0.333333,0.333333
55,2022-05-11,20:15,Matchweek 33,Wed,Away,W,5,1,Wolves,3.1,...,20,2,4.666667,0.333333,20.000000,7.333333,15.166667,0.333333,0.333333,0.333333
56,2022-05-15,14:00,Matchweek 37,Sun,Away,D,2,2,West Ham,2.5,...,14,6,4.666667,0.333333,18.333333,6.666667,14.933333,0.333333,0.000000,0.000000
57,2022-05-22,16:00,Matchweek 38,Sun,Home,W,3,2,Aston Villa,2.9,...,16,6,4.000000,1.000000,22.000000,7.000000,15.700000,1.000000,0.000000,0.333333

In [37]:
matches_rolling = matches.groupby("team").apply(lambda x: rolling_averages(x, cols, new_cols))

In [38]:
matches_rolling

                                 date   time         round  day venue result  \
team
Arsenal                 6  2020-10-04  14:00   Matchweek 4  Sun  Home      W
                        7  2020-10-17  17:30   Matchweek 5  Sat  Away      L
                        9  2020-10-25  19:15   Matchweek 6  Sun  Home      L
                        11 2020-11-01  16:30   Matchweek 7  Sun  Away      W
                        13 2020-11-08  19:15   Matchweek 8  Sun  Home      L
...                               ...    ...           ...  ...   ...    ...
Wolverhampton Wanderers 37 2022-04-30  15:00  Matchweek 35  Sat  Home      L
                        38 2022-05-07  15:00  Matchweek 36  Sat  Away      D
                        39 2022-05-11  20:15  Matchweek 33  Wed  Home      L
                        40 2022-05-15  14:00  Matchweek 37  Sun  Home      D
                        41 2022-05-22  16:00  Matchweek 38  Sun  Away      L

                            gf  ga         opponent   xg  ...  hour  day_code  \
team                                                      ...
Arsenal                 6    2   1    Sheffield Utd  0.4  ...    14         6
                        7    0   1  Manchester City  0.9  ...    17         5
                        9    0   1   Leicester City  0.9  ...    19         6
                        11   1   0   Manchester Utd  1.1  ...    16         6
                        13   0   3      Aston Villa  1.5  ...    19         6
...                         ..  ..              ...  ...  ...   ...       ...
Wolverhampton Wanderers 37   0   3         Brighton  0.6  ...    15         5
                        38   2   2          Chelsea  2.1  ...    15         5
                        39   1   5  Manchester City  0.5  ...    20         2
                        40   1   1     Norwich City  0.9  ...    14         6
                        41   1   3        Liverpool  1.1  ...    16         6

                            gf_rolling ga_rolling sh_rolling sot_rolling  \
team
Arsenal                 6     2.000000   1.333333   7.666667    3.666667
                        7     1.666667   1.666667   5.333333    3.666667
                        9     1.000000   1.666667   7.000000    3.666667
                        11    0.666667   1.000000   9.666667    4.000000
                        13    0.333333   0.666667   9.666667    2.666667
...                                ...        ...        ...         ...
Wolverhampton Wanderers 37    0.666667   1.000000   8.666667    3.333333
                        38    0.000000   1.666667   8.666667    2.333333
                        39    0.666667   2.000000  11.666667    3.000000
                        40    1.000000   3.333333  10.666667    2.666667
                        41    1.333333   2.666667  12.666667    3.666667

                           dist_rolling  fk_rolling  pk_rolling  pkatt_rolling
team
Arsenal                 6     14.733333    0.666667    0.000000       0.000000
                        7     15.766667    0.000000    0.000000       0.000000
                        9     16.733333    0.666667    0.000000       0.000000
                        11    16.033333    1.000000    0.000000       0.000000
                        13    18.033333    1.000000    0.333333       0.333333
...                                 ...         ...         ...            ...
Wolverhampton Wanderers 37    16.966667    0.000000    0.000000       0.000000
                        38    18.233333    0.333333    0.000000       0.000000
                        39    17.133333    0.333333    0.000000       0.000000
                        40    16.400000    0.333333    0.000000       0.000000
                        41    17.033333    0.666667    0.000000       0.000000

[1448 rows x 38 columns]

In [39]:
matches_rolling = matches_rolling.droplevel('team')

In [40]:
matches_rolling

,date,time,round,day,venue,result,gf,ga,opponent,xg,...,hour,day_code,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
6,2020-10-04,14:00,Matchweek 4,Sun,Home,W,2,1,Sheffield Utd,0.4,...,14,6,2.000000,1.333333,7.666667,3.666667,14.733333,0.666667,0.000000,0.000000
7,2020-10-17,17:30,Matchweek 5,Sat,Away,L,0,1,Manchester City,0.9,...,17,5,1.666667,1.666667,5.333333,3.666667,15.766667,0.000000,0.000000,0.000000
9,2020-10-25,19:15,Matchweek 6,Sun,Home,L,0,1,Leicester City,0.9,...,19,6,1.000000,1.666667,7.000000,3.666667,16.733333,0.666667,0.000000,0.000000
11,2020-11-01,16:30,Matchweek 7,Sun,Away,W,1,0,Manchester Utd,1.1,...,16,6,0.666667,1.000000,9.666667,4.000000,16.033333,1.000000,0.000000,0.000000
13,2020-11-08,19:15,Matchweek 8,Sun,Home,L,0,3,Aston Villa,1.5,...,19,6,0.333333,0.666667,9.666667,2.666667,18.033333,1.000000,0.333333,0.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37,2022-04-30,15:00,Matchweek 35,Sat,Home,L,0,3,Brighton,0.6,...,15,5,0.666667,1.000000,8.666667,3.333333,16.966667,0.000000,0.000000,0.000000
38,2022-05-07,15:00,Matchweek 36,Sat,Away,D,2,2,Chelsea,2.1,...,15,5,0.000000,1.666667,8.666667,2.333333,18.233333,0.333333,0.000000,0.000000
39,2022-05-11,20:15,Matchweek 33,Wed,Home,L,1,5,Manchester City,0.5,...,20,2,0.666667,2.000000,11.666667,3.000000,17.133333,0.333333,0.000000,0.000000
40,2022-05-15,14:00,Matchweek 37,Sun,Home,D,1,1,Norwich City,0.9,...,14,6,1.000000,3.333333,10.666667,2.666667,16.400000,0.333333,0.000000,0.000000
41,2022-05-22,16:00,Matchweek 38,Sun,Away,L,1,3,Liverpool,1.1,...,16,6,1.333333,2.666667,12.666667,3.666667,17.033333,0.666667,0.000000,0.000000

In [41]:
matches_rolling.index = range(matches_rolling.shape[0])

In [42]:
def make_predictions(data, predictors):
    train = data[data["date"] < '2022-01-01']
    test = data[data["date"] > '2022-01-01']
    rf.fit(train[predictors], train["target"])
    preds = rf.predict(test[predictors])
    combined = pd.DataFrame(dict(actual=test["target"], predicted=preds), index=test.index)
    error = precision_score(test["target"], preds)
    return combined, error

In [43]:
combined, error = make_predictions(matches_rolling, predictors + new_cols)

In [44]:
error

0.6027397260273972

In [45]:
combined = combined.merge(matches_rolling[["date", "team", "opponent", "result"]], left_index=True, right_index=True)

In [46]:
combined

,actual,predicted,date,team,opponent,result
55,0,0,2022-01-23,Arsenal,Burnley,D
56,1,1,2022-02-10,Arsenal,Wolves,W
57,1,0,2022-02-19,Arsenal,Brentford,W
58,1,1,2022-02-24,Arsenal,Wolves,W
59,1,1,2022-03-06,Arsenal,Watford,W
...,...,...,...,...,...,...
1443,0,0,2022-04-30,Wolverhampton Wanderers,Brighton,L
1444,0,0,2022-05-07,Wolverhampton Wanderers,Chelsea,D
1445,0,0,2022-05-11,Wolverhampton Wanderers,Manchester City,L
1446,0,0,2022-05-15,Wolverhampton Wanderers,Norwich City,D
1447,0,0,2022-05-22,Wolverhampton Wanderers,Liverpool,L

In [47]:
class MissingDict(dict):
    __missing__ = lambda self, key: key

map_values = {"Brighton and Hove Albion": "Brighton", "Manchester United": "Manchester Utd", "Newcastle United": "Newcastle Utd", "Tottenham Hotspur": "Tottenham", "West Ham United": "West Ham", "Wolverhampton Wanderers": "Wolves"} 
mapping = MissingDict(**map_values)

In [48]:
combined["new_team"] = combined["team"].map(mapping)

In [49]:
merged = combined.merge(combined, left_on=["date", "new_team"], right_on=["date", "opponent"])

In [50]:
merged

,actual_x,predicted_x,date,team_x,opponent_x,result_x,new_team_x,actual_y,predicted_y,team_y,opponent_y,result_y,new_team_y
0,0,0,2022-01-23,Arsenal,Burnley,D,Arsenal,0,0,Burnley,Arsenal,D,Burnley
1,1,1,2022-02-10,Arsenal,Wolves,W,Arsenal,0,0,Wolverhampton Wanderers,Arsenal,L,Wolves
2,1,0,2022-02-19,Arsenal,Brentford,W,Arsenal,0,0,Brentford,Arsenal,L,Brentford
3,1,1,2022-02-24,Arsenal,Wolves,W,Arsenal,0,0,Wolverhampton Wanderers,Arsenal,L,Wolves
4,1,1,2022-03-06,Arsenal,Watford,W,Arsenal,0,0,Watford,Arsenal,L,Watford
...,...,...,...,...,...,...,...,...,...,...,...,...,...
383,0,0,2022-04-30,Wolverhampton Wanderers,Brighton,L,Wolves,1,0,Brighton and Hove Albion,Wolves,W,Brighton
384,0,0,2022-05-07,Wolverhampton Wanderers,Chelsea,D,Wolves,0,0,Chelsea,Wolves,D,Chelsea
385,0,0,2022-05-11,Wolverhampton Wanderers,Manchester City,L,Wolves,1,1,Manchester City,Wolves,W,Manchester City
386,0,0,2022-05-15,Wolverhampton Wanderers,Norwich City,D,Wolves,0,0,Norwich City,Wolves,D,Norwich City
387,0,0,2022-05-22,Wolverhampton Wanderers,Liverpool,L,Wolves,1,0,Liverpool,Wolves,W,Liverpool

In [51]:
merged[(merged["predicted_x"] == 1) & (merged["predicted_y"] ==0)]["actual_x"].value_counts()

1    43
0    28
Name: actual_x, dtype: int64