In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_absolute_percentage_error

from sklearn.ensemble import AdaBoostRegressor

In [2]:
df = pd.read_csv('hotData.csv')

In [3]:
df.head()

,goals,xg,crosses,boxtouches,passes,progpasses,takeons,progruns,tackles,interceptions,...,64,65,66,67,68,69,70,71,72,73
0,0.055385,-0.119231,-0.020769,0.236154,-0.781538,-0.649231,-0.407692,-0.568462,-0.578462,-0.444615,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,-0.243077,0.063846,-0.090769,-0.287692,-0.704615,-0.441538,-0.098462,-0.383077,-0.722308,-0.606154,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,-0.420000,-0.230000,-0.150769,-0.435385,-0.687692,-0.408462,-0.256923,-0.586154,-0.629231,-0.560000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,-0.070769,-0.368462,-0.493846,-0.247692,-0.681538,-0.536923,-0.210000,-0.427692,-0.539231,-0.622308,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.153077,0.197692,0.030000,0.088462,-0.665385,-0.347692,-0.200000,-0.407692,-0.646154,-0.612308,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [7]:
y = df['results']
X = df.drop(columns=['results'])

X_train, X_test, y_train, y_test = train_test_split(
     X, y, test_size=0.09, random_state=10)

In [8]:
regr = AdaBoostRegressor(n_estimators=100)

In [9]:
regr.fit(X_train, y_train)

AdaBoostRegressor(n_estimators=100)

In [10]:
y_pred = regr.predict(X_test)

In [11]:
print('Neural Network Regression')
print('r2 score: '+str(r2_score(y_test, y_pred)))
print('RMSE : '+str(np.sqrt(mean_squared_error(y_test, y_pred))))
print('MSE: '+str(mean_squared_error(y_test, y_pred)))
print('MAE: '+str(mean_absolute_error(y_test, y_pred)))
print('MAPE: '+str(mean_absolute_percentage_error(y_test, y_pred)))

Neural Network Regression
r2 score: 0.3513740383046161
RMSE : 7.442985312467342
MSE: 55.398030361604576
MAE: 5.958258456155656
MAPE: 0.9196178902233723

In [12]:
# MAPE: 0.27990169259785563

In [13]:
data = {'y_test': y_test, 'y_pred': y_pred}
new_df = pd.DataFrame(data)
diff = (new_df['y_test'] - (new_df['y_pred'])).abs()
new_df['diff'] = diff
new_df = new_df.sort_values(by='diff', ascending=True)

In [14]:
new_df

     y_test     y_pred       diff
211      13  13.354167   0.354167
98        9   9.731250   0.731250
250      10   9.222222   0.777778
178      13  13.906667   0.906667
272       9  10.267123   1.267123
35       23  21.601504   1.398496
262      23  20.828025   2.171975
274      24  21.601504   2.398496
261      14  10.129310   3.870690
194       9  12.952941   3.952941
176      19  23.144737   4.144737
170      18  22.736842   4.736842
47       22  16.737374   5.262626
157      15   9.352941   5.647059
26        4  10.426752   6.426752
244       2   8.761290   6.761290
113       4  10.840000   6.840000
43       29  22.153061   6.846939
235       2   8.884058   6.884058
25       30  21.821656   8.178344
100       1   9.183333   8.183333
164      24  14.642857   9.357143
154      21   8.589147  12.410853
148      29  15.395833  13.604167
149      25   9.402597  15.597403
209      30  13.796407  16.203593