In [170]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.ticker as ticker
import matplotlib.ticker as plticker
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

import matplotlib.pyplot as pyplot
import seaborn as sns

In [171]:
df = pd.read_csv('WC-stats.csv')

In [172]:
df.head()

,Unnamed: 0,goals_z,xg_z,crosses_z,boxtouches_z,passes_z,progpasses_z,takeons_z,progruns_z,tackles_z,interceptions_z,clearances_z,blocks_z,aerials_z,fouls_z,fouled_z,nsxg_z,results
0,Brazil98,0.423077,0.146923,-0.136154,-0.030000,0.429231,0.037692,0.244615,-0.220000,0.216154,0.270000,-0.076923,-0.097692,-0.020000,-0.224615,0.100769,-0.124615,2
1,Brazil94,0.216923,0.348462,0.031538,0.158462,0.835385,0.626923,0.270000,0.266923,1.143846,0.834615,-0.059231,-0.134615,0.196923,-0.016923,0.033846,0.146923,1
2,Brazil90,0.113846,0.392308,0.599231,0.513846,0.833077,0.405385,0.521538,1.139231,1.109231,0.859231,0.084615,0.103077,0.683846,0.213846,0.353846,0.786923,9
3,Brazil86,0.479231,0.609231,0.227692,0.450769,0.770769,0.042308,0.337692,0.927692,0.506923,1.015385,0.020769,0.381538,0.038462,0.039231,0.022308,0.692308,5
4,Brazil82,0.877692,0.773846,0.428462,0.659231,0.754615,0.335385,0.023077,0.638462,0.493846,0.637692,-0.117692,-0.033846,0.572308,-0.016154,-0.096923,0.890769,5

In [173]:
df = df.rename(columns={"Unnamed: 0": "country"}, errors="raise")

In [174]:
sers = df['country']

In [175]:
year = []
count = 0
for i in sers:
    num = (((i[-2]) + i[-1]))
    year.append(int(num))

In [177]:
len(year)

257

In [178]:
df['year'] = year

In [179]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 257 entries, 0 to 256
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   country          257 non-null    object
 1   goals_z          257 non-null    float64
 2   xg_z             257 non-null    float64
 3   crosses_z        257 non-null    float64
 4   boxtouches_z     257 non-null    float64
 5   passes_z         257 non-null    float64
 6   progpasses_z     257 non-null    float64
 7   takeons_z        257 non-null    float64
 8   progruns_z       257 non-null    float64
 9   tackles_z        257 non-null    float64
 10  interceptions_z  257 non-null    float64
 11  clearances_z     257 non-null    float64
 12  blocks_z         257 non-null    float64
 13  aerials_z        257 non-null    float64
 14  fouls_z          257 non-null    float64
 15  fouled_z         257 non-null    float64
 16  nsxg_z           257 non-null    float64
 17  results          257 non-null    int64
 18  year             257 non-null    int64
dtypes: float64(16), int64(2), object(1)
memory usage: 38.3+ KB

In [180]:
df['year'].value_counts().sum()

257

In [181]:
df

,country,goals_z,xg_z,crosses_z,boxtouches_z,passes_z,progpasses_z,takeons_z,progruns_z,tackles_z,interceptions_z,clearances_z,blocks_z,aerials_z,fouls_z,fouled_z,nsxg_z,results,year
0,Brazil98,0.423077,0.146923,-0.136154,-0.030000,0.429231,0.037692,0.244615,-0.220000,0.216154,0.270000,-0.076923,-0.097692,-0.020000,-0.224615,0.100769,-0.124615,2,98
1,Brazil94,0.216923,0.348462,0.031538,0.158462,0.835385,0.626923,0.270000,0.266923,1.143846,0.834615,-0.059231,-0.134615,0.196923,-0.016923,0.033846,0.146923,1,94
2,Brazil90,0.113846,0.392308,0.599231,0.513846,0.833077,0.405385,0.521538,1.139231,1.109231,0.859231,0.084615,0.103077,0.683846,0.213846,0.353846,0.786923,9,90
3,Brazil86,0.479231,0.609231,0.227692,0.450769,0.770769,0.042308,0.337692,0.927692,0.506923,1.015385,0.020769,0.381538,0.038462,0.039231,0.022308,0.692308,5,86
4,Brazil82,0.877692,0.773846,0.428462,0.659231,0.754615,0.335385,0.023077,0.638462,0.493846,0.637692,-0.117692,-0.033846,0.572308,-0.016154,-0.096923,0.890769,5,82
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
252,Colombia90,0.073077,0.004615,-0.013077,0.047692,0.873846,0.790769,0.200769,-0.084615,0.260000,1.156923,-0.149231,0.108462,-0.160769,0.427692,0.540769,-0.071538,14,90
253,Colombia94,0.013846,0.266923,-0.103846,0.443077,1.092308,0.601538,0.500769,-0.234615,0.880000,1.216154,-0.359231,0.058462,-0.150000,0.290000,-0.176154,0.568462,19,94
254,Colombia98,-0.261538,-0.169231,-0.216923,-0.154615,0.068462,-0.088462,0.183077,0.316154,-0.177692,0.080769,-0.166154,-0.361538,-0.270000,0.290000,0.245385,-0.173077,21,98
255,Colombia14,0.781538,0.256154,0.016923,0.298462,-0.303077,-0.243846,0.117692,0.115385,-0.035385,-0.245385,-0.143077,-0.047692,-0.237692,0.343846,0.417692,0.353077,5,14
256,Colombia18,0.313077,-0.103077,0.029231,-0.319231,-0.093846,-0.152308,-0.142308,-0.181538,0.058462,-0.141538,0.016923,-0.018462,0.121538,0.212308,0.083077,-0.171538,9,18

In [182]:
country = df['country']

In [183]:
country

0        Brazil98
1        Brazil94
2        Brazil90
3        Brazil86
4        Brazil82
          ...
252    Colombia90
253    Colombia94
254    Colombia98
255    Colombia14
256    Colombia18
Name: country, Length: 257, dtype: object

In [184]:
country = []
for i in sers:
    country.append(i[:-2])

In [185]:
df['country'] = country

In [186]:
df

,country,goals_z,xg_z,crosses_z,boxtouches_z,passes_z,progpasses_z,takeons_z,progruns_z,tackles_z,interceptions_z,clearances_z,blocks_z,aerials_z,fouls_z,fouled_z,nsxg_z,results,year
0,Brazil,0.423077,0.146923,-0.136154,-0.030000,0.429231,0.037692,0.244615,-0.220000,0.216154,0.270000,-0.076923,-0.097692,-0.020000,-0.224615,0.100769,-0.124615,2,98
1,Brazil,0.216923,0.348462,0.031538,0.158462,0.835385,0.626923,0.270000,0.266923,1.143846,0.834615,-0.059231,-0.134615,0.196923,-0.016923,0.033846,0.146923,1,94
2,Brazil,0.113846,0.392308,0.599231,0.513846,0.833077,0.405385,0.521538,1.139231,1.109231,0.859231,0.084615,0.103077,0.683846,0.213846,0.353846,0.786923,9,90
3,Brazil,0.479231,0.609231,0.227692,0.450769,0.770769,0.042308,0.337692,0.927692,0.506923,1.015385,0.020769,0.381538,0.038462,0.039231,0.022308,0.692308,5,86
4,Brazil,0.877692,0.773846,0.428462,0.659231,0.754615,0.335385,0.023077,0.638462,0.493846,0.637692,-0.117692,-0.033846,0.572308,-0.016154,-0.096923,0.890769,5,82
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
252,Colombia,0.073077,0.004615,-0.013077,0.047692,0.873846,0.790769,0.200769,-0.084615,0.260000,1.156923,-0.149231,0.108462,-0.160769,0.427692,0.540769,-0.071538,14,90
253,Colombia,0.013846,0.266923,-0.103846,0.443077,1.092308,0.601538,0.500769,-0.234615,0.880000,1.216154,-0.359231,0.058462,-0.150000,0.290000,-0.176154,0.568462,19,94
254,Colombia,-0.261538,-0.169231,-0.216923,-0.154615,0.068462,-0.088462,0.183077,0.316154,-0.177692,0.080769,-0.166154,-0.361538,-0.270000,0.290000,0.245385,-0.173077,21,98
255,Colombia,0.781538,0.256154,0.016923,0.298462,-0.303077,-0.243846,0.117692,0.115385,-0.035385,-0.245385,-0.143077,-0.047692,-0.237692,0.343846,0.417692,0.353077,5,14
256,Colombia,0.313077,-0.103077,0.029231,-0.319231,-0.093846,-0.152308,-0.142308,-0.181538,0.058462,-0.141538,0.016923,-0.018462,0.121538,0.212308,0.083077,-0.171538,9,18

In [187]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 257 entries, 0 to 256
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   country          257 non-null    object
 1   goals_z          257 non-null    float64
 2   xg_z             257 non-null    float64
 3   crosses_z        257 non-null    float64
 4   boxtouches_z     257 non-null    float64
 5   passes_z         257 non-null    float64
 6   progpasses_z     257 non-null    float64
 7   takeons_z        257 non-null    float64
 8   progruns_z       257 non-null    float64
 9   tackles_z        257 non-null    float64
 10  interceptions_z  257 non-null    float64
 11  clearances_z     257 non-null    float64
 12  blocks_z         257 non-null    float64
 13  aerials_z        257 non-null    float64
 14  fouls_z          257 non-null    float64
 15  fouled_z         257 non-null    float64
 16  nsxg_z           257 non-null    float64
 17  results          257 non-null    int64
 18  year             257 non-null    int64
dtypes: float64(16), int64(2), object(1)
memory usage: 38.3+ KB